# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=260)),
                ('course_name', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(choices=[('whole', 'Course as a whole'), ('txtbk_oa', 'Textbook Overall'), ('instr_oa', 'Instructor Overall'), ('c_content', 'Course Content'), ('instr_contrib', "Instructor's Contribution"), ('instr_effect', "Instructor's Effectiveness"), ('instr_interest', "Instructor's Interest"), ('amt_learned', 'Amount learned'), ('grading_tech', 'Grading Techniques'), ('relev_of_hw', 'Relevance and usefulness of homework')], max_length=20)),
                ('excellent', models.IntegerField()),
                ('very_good', models.IntegerField()),
                ('good', models.IntegerField()),
                ('fair', models.IntegerField()),
                ('poor', models.IntegerField()),
                ('very_poor', models.IntegerField()),
                ('median', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=40)),
                ('standing', models.CharField(max_length=30)),
                ('quarter', models.CharField(max_length=4)),
                ('surveyed', models.IntegerField()),
                ('enrolled', models.IntegerField()),
                ('lecture_form', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Teacher who taught course')),
            ],
        ),
        migrations.AddField(
            model_name='criteria',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Teacher', verbose_name='Teacher Evaluations'),
        ),
    ]
